services:
  web:
    build: .
    ports:
      - "80:80"
    volumes:
      - "./:/var/www/html"
    networks:
      - default
  #mysql:
  #  image: mysql:5.7
  #  ports:
  #    - "3306:3306"
  #  environment:
  #    MYSQL_ROOT_PASSWORD: tiger
  #    MYSQL_DATABASE: data
  #  networks:
  #    - default
